language: ruby
sudo: false
rvm:
  - 2.3.1
  - 2.3.4
  - 2.4.1
  - 2.5.0
before_install:
  - gem install bundler -v 1.10.6
install:
  - bundle install --jobs=1
script: bundle exec rspec --require spec_helper
